Feature/tasks
LKS007/task_manager pull request #26
Opened 2019-01-20 20:19 UTC by LKS007

2019-01-21 08:06 UTC, Andrew8xx8 requested changes

2019-01-21 08:06 UTC, Andrew8xx8 commented on app/javascript/packs/components/AddPopup.js
> +    if (response.statusText == 'Created') {
Согласно RESTful API, для корректной обработки ответов нужно использовать статусы `http`. Текст никак не регламентирован и завязыватся на него не стоит.
https://www.restapitutorial.com/httpstatuscodes.html

2019-01-21 08:06 UTC, Andrew8xx8 commented on app/javascript/packs/components/AddPopup.js
> +        alert(response.status + ' - ' + response.statusText);
Обработка ошибок так не будет работать. Этот блок else никогда не выполнится, обработка ошибок в AXIOS построенна на использование Promise API и в случае ошибки будет выполнятся catch.  Посмотри пример. https://github.com/axios/axios#example

2019-01-21 08:06 UTC, Andrew8xx8 commented on app/javascript/packs/components/AddPopup.js
> +      task: {
Весь этот блок можно заменить на `task: this.state`

2019-01-21 08:06 UTC, Andrew8xx8 commented on app/javascript/packs/components/EditPopup.js
> +    fetch('GET', window.Routes.api_v1_task_path(cardId, {format: 'json'})).then(({data}) => {
Настрой в webpack параметр `globals` так чтобы импортировать Routes, а не брать из window.
```
import Routes from 'routes';
```

2019-01-21 08:06 UTC, Andrew8xx8 commented on app/javascript/packs/components/EditPopup.js
> +        alert('Update failed! ' + response.status + ' - ' + response.statusText);
не используй склеивание, используй интерполяцию `${a} — ?${b}`

2019-01-21 08:06 UTC, Andrew8xx8 commented on app/javascript/packs/components/EditPopup.js
> +        <Modal show={this.props.show} onHide={this.props.onClose}>
Если нужно более одного пропса использовать, используй object destructuring из es6
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment
Посмотри все места где ты используешь `this.props` или `this.state`

2019-01-21 08:06 UTC, Andrew8xx8 commented on app/javascript/packs/components/TaskBoard.js
> +    return fetch('GET', window.Routes.api_v1_tasks_path({ q: { state_eq: state }, page: page, per_page: 10, format: 'json' })).then(({data}) => {
Сделай метод `fetchJson` в fetch и перенеси `{ format: 'json' }` туда. В этом файле этот лишний визуальный шум, мы и так предполагаем что все API у нас формата json.
Так же есть принцип единственности ответственности и разделения на слои абстракции, компонет в котором находится логика отображения не должен знать ничего о том каким образом к нему попали данные, это обязанность слоя абстракции ниже, ответсвтенность которого — пересылка данных

2019-01-21 12:15 UTC, LKS007 commented on app/javascript/packs/components/AddPopup.js
> +      task: {
Похоже, что не совсем:
здесь нужен assignee_id, а в state хранится объект assignee. Выходит, я передам ненужную информацию с assignee, и все равно нужно будет добавлять свойство assigne_id

2019-01-24 10:03 UTC, Andrew8xx8 approved these changes

2019-01-24 15:59 UTC, merged