Feature/assignee 2 0
LKS007/task_manager pull request #27
Opened 2019-01-24 19:19 UTC by LKS007

2019-01-25 11:25 UTC, artempartos requested changes

2019-01-25 11:25 UTC, artempartos commented on app/javascript/packs/components/UserSelect.js
> +	render() {
что-то с разметкой

2019-01-25 11:25 UTC, artempartos commented on app/serializers/user_serializer.rb
> +    object.id.to_s
зачем id становится строкой?

2019-01-25 11:25 UTC, artempartos commented on app/javascript/packs/components/UserSelect.js
> +    return option.first_name + ' ' + option.last_name
используй конкатенацию и деструктуризацию es6

2019-01-25 11:25 UTC, artempartos commented
хорошо бы еще добавить eslint в travis ci

2019-01-26 10:58 UTC, LKS007 commented
Добавил ESlint, внес некоторые правки по eslint, так же поправил замечания с прошлой проверки!

2019-01-26 12:30 UTC, artempartos commented on app/serializers/user_serializer.rb
>    def id
зачем нужен этот метод? id и так возьмется у объекта

2019-01-26 18:19 UTC, LKS007 commented on app/serializers/user_serializer.rb
>    def id
Да, кажется, в нем нет необходимости! поправил, спасибо

2019-01-26 18:25 UTC, artempartos commented
👍

2019-01-26 18:36 UTC, merged